model_params:
  latent_dim: 128
  discriminator: [16, 4]
  input_features: 258
  channels: [256, 256, 128]
  re_channels: [128, 64, 16]
  kernel_size: 3
  drop_out: 0.2
  time_dim: 258


exp_params:
  LR: 0.1
  epoch: 10
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.1
  manual_seed: 1265
  batch_size: 16

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"

